### PR TITLE
Replaces Syntastic by ALE

### PR DESCRIPTION
**Pull request by edygar**

### CODE REVIEW

**Comment by lfilho** [comment]
Thanks, but... Rationale? :-)

**Comment by edygar** [comment]
This is just a suggestion ;)

For me it has been working very well, asynchronously linting and fixing on file save. Errors showing up during typing makes it way faster to fix them and there's no block as syntastic could block some times for larger files.

**Comment by lfilho** [comment]
... for example...

- why not https://github.com/neomake/neomake ?
- what about the dozens of configurations for syntastic you just got rid of?

Also, by doing `let g:ale_linters = {'javascript': ['eslint']}` you're enabling **ONLY** javascript syntax checking (see https://github.com/w0rp/ale#5i-how-do-i-disable-particular-linters). What about all the others?

Man, these kind of PRs must provide a seamless experience, a drop-in replacement, be as retrocompatible as possible. But if I merge this PR as it is, it will break everything and I'll loose a lot of customizations done via syntastic...

**Comment by edygar** [comment]
- Why not [neomake](https://github.com/neomake/neomake)?
Although ALE is more recent, it has more Github stars, good amount of support for various languages and a very decent Fixer support. Also, It's been a seamless replacement.

- What about the dozens of configurations for syntastic you just got rid of?
ALE has good amount of defaults, the explicit definition isn't really necessary there but It's literally the same case scenario as `g:syntastic_javascript_checkers`, `eslint` is the default, user should override in `.vimrc.after`. It isn't a drop-in replacement. The syntax of both are very distinct as their behavior. Instantly receive feedback feels magic and in my opinion, it worths the change ;)

As for this PR, its a on going development, *IF* you have *ANY* interest. I just need your thoughts.

**Comment by lfilho** [comment]
Yes I do have interest in a async linter!! I was with both of these options in the back of my mind, but I have feeling I have read more people saying good things about neomake somewhere... Doesn't matter much... Keep up the good work! #win 

- What I meant for a drop-in replacement is from the UX perspective, not the plugin's syntaxes or configurations. That is: someone using this repo, on updating, shouldn't have to "learn" or "be aware" of under the hood changes going on. In other words, his linting workflow shouldn't change (only be improved with the new async behaviour).
- If we're changing the expected linting workflow somehow (for example, linting as we type instead of on save), we should point out on the PR description that this is happening and what are the costs (more CPU usage, which means that might get sluggish on simpler machines, also means more battery drainage...). These things should be explicited so we can have a conversation in the PR page and then decide whether those changes are worth it, or whether we should change at least change some configs here and there until we reach a nice and agreeable point :-) 👍 
- The line `let g:ale_linters = {'javascript': ['eslint']}` is not the same as the existing syntastic one. The existing one configures syntastic to use eslint for its javascript linter. The one you're proposing **disables all other linters** while enabling `eslint` for javascript. Got it? (At least that's what their documentation says).

**Comment by lfilho** [comment]
ping @edygar .
(Also, there's a conflict in this branch now 😊 )

**Comment by edygar** [comment]
Thanks, I've just updated and fixed the conflicts, but I hadn't much progress on suppressing some warnings of the tidy.

**Pull request merged**
