### PR TITLE
Ready to Merge: Get Install on Linux Working 

### PR DESCRIPTION
**Pull request by daxgames**
I have been using [skwp/dotfiles](https://github.com/skwp/dotfiles) since 2013 and have been wanting to play with `nvim`.

I use [skwp/dotfiles](https://github.com/skwp/dotfiles) on both MacOS and Linux and would like to have a single solution that can work with `nvim` on both as well as [skwp/dotfiles](https://github.com/skwp/dotfiles) does.

I was aware of your fork and have tried it before without much success on Linux.  Today I decided to try and fix the issues I saw when installing just so I could actually start using it and see if I want to move to it or create my own fork of it as I did for [skwp/dotfiles](https://github.com/skwp/dotfiles).

## What was not working

Failing during install on Linux because `brew` was not in the path after installing it.

## How it works now

The change is this PR allows `install.sh` on Linux to complete without error.  As I have modified things it now installs on Linux and only  `:PlugInstall` once `nvim` is running and it is completely functional as far as I can tell.

Please let me knwo If I missed anything.

_Note: I renamed my [skwp/dotfiles](https://github.com/skwp/dotfiles) `~/.yadr` folder and installed using my changes from another branch in my fork.  I have not done a fresh install on a clean system._

## Tested On

- Ubuntu 22.04
- AmazonLinux 2

### Linux brew env setup during the rakefle run is not as dynamic as I would like.

- This is the only way I could make it work though.

### .yadr/Brewfile

Changed the order from alphabetical.  Doubt this matters but below are my observations.

- `ffmpeg`, `rename` Hung FOREVER on first run `install.sh` and eventually failed to install.
  - Running `brew bundle install` manually a second time installed both successfully.
  - I moved both of them to the end of the list, deleted `/home/linuxbrew` folder and reran `yadr` install
    - `ffmpeg` installed this time
    - `rename` did not install this time.
      - Running `brew bundle install` manually a second time installed `rename` successfully.

If I have put things in the wrong place or any changes to the PR are required please let me know and I will fix ASAP.

Thanks.
Dax

### CODE REVIEW

**Comment by daxgames** [comment]
@lfilho Also how do I change the prompt.  With `skwp/dotfiles` I could do `prompt kylewest` or drop that into a file in `~/.zsh.after/prompt.zsh` and the prompt would change.

That does not work with your fork.  I would really like to be able to change the prompt but I am locked into the below and cannot figure out how to change it:

image

**Comment by daxgames** [comment]
Took me a while to figure out I had to run `:PlugInstall` in `nvim`  manually.  Is this by design or could it be made to do it automatically?

**Comment by lfilho** [comment]
Hey @daxgames thanks a lot for the contribution. Last time (long time ago) i installed it on linux it worked, possibly Brew changed their install path in the mean time. I'll just trust your changes and tests :) I try to install them afresh in my linux box soon.

As for the Brewfile changes: i opted for alphabetical in order to minimize future diffs and make it easier to quickly see if a particular brew formula is or is not in there. If you needed to run bundle install a second time anyway (which is odd), should we keep the previous alphabetical order then? Aside this nit pick on the Brewfile, I'm ready to merge your PR, thanks!

As for changing the prompt, oof, good question. It's been a while since i needed to change prompts or looked at that area of the code, so I don't know what's happening. I'll try to have a go at it (separate from this PR of course).

**Comment by daxgames** [comment]
@lfihlo I just found some things I did wring and fixed them.

I also figured out how to change the prompt about an hour ago.  It's not pretty.

See below(from my personal branch Not the one for this PR):

- Change from `powerlevel9k` to `skwp` [here](https://github.com/daxgames/dotfiles/blob/7ebc4a6b423d5db83fdec7f86b6d64aa4e36a51f/zsh/prezto-override/zpreztorc#L82-L85)
- Create `~/.zsh.before/fix_prompt.zsh` script to delete a symlink created by your [Rakefile](https://github.com/daxgames/dotfiles/blob/7ebc4a6b423d5db83fdec7f86b6d64aa4e36a51f/Rakefile#L230)`.  

Only then could I change the prompt using the normal methods described above.

I am switching back and forth between yours and mine until I am happy by simply checking out the branch I want to run and running `rake update` so I am trying to make it as automatic as possible.  Actually I could do it a lot faster with a simple shell script but I am lazy. :-)

Something is still off in my prompt after changing it but it is a LOT closer to what I am looking for.

I think I am done with the PR though.

**Comment by lfilho** [comment]
I see. Cheer!

I'm merging the PR but FYI will revert the Brewfile to be sorted again until we have better evidence that the sorting was causing any issues, ok? 

Thanks a lot for your contribution. Let me know if you any more good ideas :)

**Comment by daxgames** [comment]
No problem.  Will do.

**Pull request merged**
