### PR TITLE
Adds a Fish-like autosuggestions

### PR DESCRIPTION
**Pull request by edygar**

### CODE REVIEW

**Comment by lfilho** [comment]
Thanks for your contribution, man!

Could you remove the "Edygar"-specific stuff from the PR? :-)
Could also elaborate what each change aims to provide?

Thanks

**Comment by lfilho** [comment]
Also, your previous changes related to easymotion piggybacked their way into this PR...
I have accepted that PR so you can rebase this branch now and only propose the zsh suggestions

**Comment by edygar** [comment]
Sorry, xD I had merged unwisely my master branch into that, but now it's fixed.

**Comment by lfilho** [comment]
The mapping was <kbd>ctrl</kbd> + <kbd>n</kbd> before, wasn't it? I prefer it as it's the same mapping used for completing suggestions in vim...

**Comment by edygar** [comment]
Nice, I wasn't sure about it. <kbd>ctrl</kbd>+<kbd>n</kbd> it is once again

**Comment by edygar** [comment]
In the end, https://github.com/lfilho/dotfiles/issues/16 wasn't related to this PR, which is now ready to be merged! ;)

**Comment by lfilho** [comment]
I was about to merge this but found that prezto actually already has this module: https://github.com/sorin-ionescu/prezto/tree/master/modules/autosuggestions

So it's only a matter of enabling it... Could you update your PR to reflect that, please?

Thanks again

**Comment by edygar** [comment]
Nice! I'm going to close this PR and open another as the 'implementation' of both are way different.

**Pull request closed without merging**
